"""Initial migration (renamed models)

Revision ID: 732cad25b9c9
Revises: 
Create Date: 2025-12-19 23:15:53.988781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732cad25b9c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_rubric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('SYSTEM_DESIGN', 'BEHAVIORAL', 'CODING', 'TECHNICAL', 'COMMUNICATION', name='rubriccategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_rubric_id'), 'evaluation_rubric', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_rubric_name'), 'evaluation_rubric', ['name'], unique=False)
    op.create_index(op.f('ix_evaluation_rubric_version'), 'evaluation_rubric', ['version'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('created', 'in_progress', 'awaiting_feedback', 'completed', 'cancelled', name='sessionstatus'), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('skill_targets', sa.JSON(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('question_context', sa.Text(), nullable=True),
    sa.Column('response_audio_url', sa.String(length=500), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_status', sa.String(length=50), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_id'), 'assessment', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_user_id'), 'assessment', ['user_id'], unique=False)
    op.create_table('user_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('previous_progress', sa.Integer(), nullable=True),
    sa.Column('is_strength', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skill_id'), 'user_skill', ['id'], unique=False)
    op.create_index(op.f('ix_user_skill_skill_id'), 'user_skill', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_skill_user_id'), 'user_skill', ['user_id'], unique=False)
    op.create_table('weekly_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='goalpriority'), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_goal_id'), 'weekly_goal', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_goal_user_id'), 'weekly_goal', ['user_id'], unique=False)
    op.create_table('code_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('python', 'javascript', 'typescript', name='codelanguage'), nullable=False),
    sa.Column('code_text', sa.Text(), nullable=False),
    sa.Column('result_output', sa.Text(), nullable=True),
    sa.Column('error_output', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_used_mb', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_submission_assessment_id'), 'code_submission', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_code_submission_id'), 'code_submission', ['id'], unique=False)
    op.create_table('drawing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('drawing_json', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawing_assessment_id'), 'drawing', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_drawing_id'), 'drawing', ['id'], unique=False)
    op.create_table('feedback_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('rubric_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='feedbackstatus'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_template_version', sa.String(length=50), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('criterion_scores', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('detailed_feedback', sa.Text(), nullable=True),
    sa.Column('safety_flags', sa.JSON(), nullable=True),
    sa.Column('content_filtered', sa.Boolean(), nullable=False),
    sa.Column('refusal_reason', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['rubric_id'], ['evaluation_rubric.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_run_assessment_id'), 'feedback_run', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_feedback_run_id'), 'feedback_run', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_run_prompt_id'), 'feedback_run', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_feedback_run_rubric_id'), 'feedback_run', ['rubric_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'AI', name='chatsender'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_assessment_id'), 'messages', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('practice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_run_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('practice_type', sa.Enum('practice_question', 'code_exercise', 'concept_review', 'mock_scenario', name='practicetype'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='practicedifficulty'), nullable=False),
    sa.Column('target_weakness', sa.String(length=255), nullable=True),
    sa.Column('target_skill', sa.String(length=255), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('hints', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'skipped', name='practicestatus'), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_run_id'], ['feedback_run.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_feedback_run_id'), 'practice', ['feedback_run_id'], unique=False)
    op.create_index(op.f('ix_practice_id'), 'practice', ['id'], unique=False)
    op.create_index(op.f('ix_practice_user_id'), 'practice', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_user_id'), table_name='practice')
    op.drop_index(op.f('ix_practice_id'), table_name='practice')
    op.drop_index(op.f('ix_practice_feedback_run_id'), table_name='practice')
    op.drop_table('practice')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_assessment_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_feedback_run_rubric_id'), table_name='feedback_run')
    op.drop_index(op.f('ix_feedback_run_prompt_id'), table_name='feedback_run')
    op.drop_index(op.f('ix_feedback_run_id'), table_name='feedback_run')
    op.drop_index(op.f('ix_feedback_run_assessment_id'), table_name='feedback_run')
    op.drop_table('feedback_run')
    op.drop_index(op.f('ix_drawing_id'), table_name='drawing')
    op.drop_index(op.f('ix_drawing_assessment_id'), table_name='drawing')
    op.drop_table('drawing')
    op.drop_index(op.f('ix_code_submission_id'), table_name='code_submission')
    op.drop_index(op.f('ix_code_submission_assessment_id'), table_name='code_submission')
    op.drop_table('code_submission')
    op.drop_index(op.f('ix_weekly_goal_user_id'), table_name='weekly_goal')
    op.drop_index(op.f('ix_weekly_goal_id'), table_name='weekly_goal')
    op.drop_table('weekly_goal')
    op.drop_index(op.f('ix_user_skill_user_id'), table_name='user_skill')
    op.drop_index(op.f('ix_user_skill_skill_id'), table_name='user_skill')
    op.drop_index(op.f('ix_user_skill_id'), table_name='user_skill')
    op.drop_table('user_skill')
    op.drop_index(op.f('ix_assessment_user_id'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_id'), table_name='assessment')
    op.drop_table('assessment')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_evaluation_rubric_version'), table_name='evaluation_rubric')
    op.drop_index(op.f('ix_evaluation_rubric_name'), table_name='evaluation_rubric')
    op.drop_index(op.f('ix_evaluation_rubric_id'), table_name='evaluation_rubric')
    op.drop_table('evaluation_rubric')
    # ### end Alembic commands ###
